services:

  ollama:
    image: ollama/ollama
    container_name: hackract-ollama

    ports:
      - "11434:11434"

    volumes:
      - ./models:/models
      - ollama_data:/root/.ollama

    restart: unless-stopped

volumes:
  ollama_data: