/**
 * Role-based permissions configuration
 * Each role has a set of permissions that define what actions they can perform
 *
 * Roles:
 *   ORG_ADMIN     – Organization administrator (highest privilege)
 *   PROJECT_ADMIN – Manages assigned projects, generates reports
 *   PENTESTER     – Ethical hacker / security researcher
 */

export const PERMISSIONS = {
    // User permissions
    USER_READ: 'user:read',
    USER_WRITE: 'user:write',
    USER_DELETE: 'user:delete',
    USER_MANAGE: 'user:manage',

    // Organization permissions
    ORG_READ: 'org:read',
    ORG_WRITE: 'org:write',
    ORG_DELETE: 'org:delete',
    ORG_MANAGE: 'org:manage',
    ORG_INVITE: 'org:invite',

    // Pentest permissions
    PENTEST_READ: 'pentest:read',
    PENTEST_WRITE: 'pentest:write',
    PENTEST_DELETE: 'pentest:delete',
    PENTEST_MANAGE: 'pentest:manage',

    // Finding permissions
    FINDING_READ: 'finding:read',
    FINDING_WRITE: 'finding:write',
    FINDING_DELETE: 'finding:delete',
    FINDING_VERIFY: 'finding:verify',

    // Report permissions
    REPORT_READ: 'report:read',
    REPORT_GENERATE: 'report:generate',

    // Role permissions
    ROLE_READ: 'role:read',
    ROLE_WRITE: 'role:write',
    ROLE_ASSIGN: 'role:assign',

    // AI Assistant permissions
    AI_READ: 'ai:read',
    AI_WRITE: 'ai:write',
    AI_MANAGE: 'ai:manage',

    // Audit log permissions
    AUDIT_READ: 'audit:read',
};

/**
 * Role-to-permissions mapping
 */
export const ROLE_PERMISSIONS = {
    ORG_ADMIN: [
        // Organization management (full)
        PERMISSIONS.ORG_READ,
        PERMISSIONS.ORG_WRITE,
        PERMISSIONS.ORG_DELETE,
        PERMISSIONS.ORG_MANAGE,
        PERMISSIONS.ORG_INVITE,

        // Pentest management within org
        PERMISSIONS.PENTEST_READ,
        PERMISSIONS.PENTEST_WRITE,
        PERMISSIONS.PENTEST_DELETE,
        PERMISSIONS.PENTEST_MANAGE,

        // Finding management
        PERMISSIONS.FINDING_READ,
        PERMISSIONS.FINDING_WRITE,
        PERMISSIONS.FINDING_DELETE,
        PERMISSIONS.FINDING_VERIFY,

        // Reports (view reports generated by PROJECT_ADMIN)
        PERMISSIONS.REPORT_READ,

        // User management within org
        PERMISSIONS.USER_READ,
        PERMISSIONS.USER_WRITE,
        PERMISSIONS.USER_MANAGE,

        // AI Assistant
        PERMISSIONS.AI_READ,
        PERMISSIONS.AI_WRITE,
        PERMISSIONS.AI_MANAGE,

        // Audit logs
        PERMISSIONS.AUDIT_READ,

        // Role management
        PERMISSIONS.ROLE_READ,
        PERMISSIONS.ROLE_WRITE,
        PERMISSIONS.ROLE_ASSIGN,
    ],

    PROJECT_ADMIN: [
        // Project/pentest management (scoped to assigned projects)
        PERMISSIONS.PENTEST_READ,
        PERMISSIONS.PENTEST_WRITE,
        PERMISSIONS.PENTEST_MANAGE,

        // Finding management
        PERMISSIONS.FINDING_READ,
        PERMISSIONS.FINDING_WRITE,
        PERMISSIONS.FINDING_DELETE,
        PERMISSIONS.FINDING_VERIFY,

        // Reports (generate from pentester findings)
        PERMISSIONS.REPORT_READ,
        PERMISSIONS.REPORT_GENERATE,

        // AI Assistant
        PERMISSIONS.AI_READ,
        PERMISSIONS.AI_WRITE,

        // Organization read
        PERMISSIONS.ORG_READ,

        // User read
        PERMISSIONS.USER_READ,

        // Audit logs (read)
        PERMISSIONS.AUDIT_READ,
    ],

    PENTESTER: [
        // Pentest access (own projects + assigned)
        PERMISSIONS.PENTEST_READ,
        PERMISSIONS.PENTEST_WRITE,

        // Finding management
        PERMISSIONS.FINDING_READ,
        PERMISSIONS.FINDING_WRITE,
        PERMISSIONS.FINDING_DELETE,

        // AI Assistant
        PERMISSIONS.AI_READ,
        PERMISSIONS.AI_WRITE,

        // Organization read
        PERMISSIONS.ORG_READ,

        // User read (own profile)
        PERMISSIONS.USER_READ,
    ],
};

/**
 * Get permissions for a given role type
 */
export const getPermissionsForRole = (roleType) => {
    return ROLE_PERMISSIONS[roleType] || [];
};

/**
 * Get all permissions for a user based on their roles
 */
export const getUserPermissions = (userRoles) => {
    const permissions = new Set();

    userRoles.forEach((role) => {
        const rolePerms = getPermissionsForRole(role.type);
        rolePerms.forEach((perm) => permissions.add(perm));
    });

    return Array.from(permissions);
};

/**
 * Check if user has a specific permission
 */
export const hasPermission = (userRoles, requiredPermission) => {
    const userPermissions = getUserPermissions(userRoles);
    return userPermissions.includes(requiredPermission);
};

/**
 * Check if user has any of the required permissions
 */
export const hasAnyPermission = (userRoles, requiredPermissions) => {
    return requiredPermissions.some((perm) => hasPermission(userRoles, perm));
};

/**
 * Check if user has all of the required permissions
 */
export const hasAllPermissions = (userRoles, requiredPermissions) => {
    return requiredPermissions.every((perm) => hasPermission(userRoles, perm));
};
